name: Continuous Integration

on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: jenk

    - name: Show directory
      run: pwd

    - name: List files
      run: ls -al

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test application
      run: pytest

